languages = {
    "ru": {
        "buttons": {
            "download": "Загрузить",
            "open": "Открыть",
            "settings": "Настройки",
            "clear-all": "Очистить всё",
            "apply-selection-by-region": "Применить",
            "clear-selection-by-region": "Очистить выборку",
            "delete-all-elements": "Удалить всё",
            "delete-element": "Удалить",
            "add-element": "Добавить",
            "check-file-size": "Проверить размер файла",
            "share": "Поделиться",
            "cancel": "Отмена",
            "upload-data": "Выгрузить данные",
        },
        "graph-site-map": {
            "title": "Карта",
        },
        "projection-radio": {
            "mercator": "Меркатор",
            "robinson": "Робинзон",
            "orthographic": "Ортографическая",
        },
        "hide-show-site": "Имена станций",
        "data-tab": {
            "label": "Данные",
            "graph-site-data": {
                "title": "Данные",
                "xaxis": "Время",
            },
            "selection-satellites": "Спутник",
            "selection-events": "Событие",
        },
        "tab-sampling-region": {
            "label": "Выборка по региону",
            "title-lat-lon": "Выборка по широте и долготе",
            "min-lat": "Мин. шир.",
            "max-lat": "Макс. шир.",
            "min-lon": "Мин. долг.",
            "max-lon": "Макс. долг.",
            "title-great-circle-distance": "Выборка по длине большого круга",
            "distance": "Дистанция (км)",
            "center-point-lat": "Шир. точки",
            "center-point-lon": "Долг. точки",
        },
        "tab-add-points":{
            "label": "Добавления точек",
            "name-point": "Имя",
            "point-marker": "Маркер",
            "point-lat": "Шир. точки",
            "point-lon": "Долг. точки",
            "point-color": "Цвет",
            "error": "Точка с данным именем уже существует",
            "title-add-point": "Добавление точки",
            "title-delete-point": "Удаление точки",
        },
        "tab-add-trajectory":{
            "label": "Добавление траекторий",
            "name-trajectory": "Имя",
            "trajectory-file": "Файл",
            "trajectory-color": "Цвет",
            "error-name": "Траектория с данным именем уже существует",
            "error-file": "Недопустимое расширение файла",
            "error-upload-file": "Необходимо загрузить файл",
            "title-add-trajectory": "Добавление траектории",
            "title-delete-trajectory": "Удаление траекории",
            "children": "Выберите файл",
            "example": "Пример:",
            "format": "Time, Longitude, Latitude, Hm",
            "format-example": "02:41:30, 24.8, -15.4, 300",
        },
        "download_window": {
            "label": "Дата",
            "successаfuly": "Файл загружен",
            "unsuccessаfuly": "Дата введена неверно",
            "repeat-action": "Этот файл уже загружен",
            "error": "Данный файл не существует",
            "file-size": "Размер (Гб): ",
            "unknown": "Неизвестно",
        },
        "open_window": {
            "label": "Файл",
        },
        "boot-progress-window":{
            "header": "Загрузка...",
        },
        "geo_stuctures_window":{
            "title": "Выбор метки события",
        },
        "trajectory":{
            "hm": "Мв",
            "hms": "Время",
            "error": "В этой проекции траектории отображаются некорректно. Переключитесь на Ортографическую.",
            "show-tag-sip": "Показать",
        }
    },
    "en": {
        "buttons": {
            "download": "Download",
            "open": "Open",
            "settings": "Settings",
            "clear-all": "Сlear all",
            "apply-selection-by-region": "Apply",
            "clear-selection-by-region": "Clear selection",
            "delete-all-elements": "Delete all",
            "delete-element": "Delete",
            "add-element": "Add",
            "check-file-size": "Check file size",
            "share": "Share",
            "cancel": "Cancel",
            "upload-data": "Upload data",
        },
        "graph-site-map": {
            "title": "Sites Map",
        },
        "projection-radio": {
            "mercator": "Mercator",
            "robinson": "Robinson",
            "orthographic": "Orthographic",
        },
        "hide-show-site": "Site names",
        "data-tab": {
            "label": "Data products series",
            "graph-site-data": {
                "title": "Data products series",
                "xaxis": "Time",
            },
            "selection-satellites": "Satellite",
            "selection-events": "Event",
        },
        "tab-sampling-region": {
            "label": "Sampling by region",
            "title-lat-lon": "Sampling by lat. and lon.",
            "min-lat": "Min. lat.",
            "max-lat": "Max. lat.",
            "min-lon": "Min. lon.",
            "max-lon": "Max. lon.",
            "title-great-circle-distance": "Sampling by great circle distance",
            "distance": "Distance (km)",
            "center-point-lat": "Lat. point",
            "center-point-lon": "Lon. point",
        },
        "tab-add-points":{
            "label": "Adding points",
            "name-point": "Name",
            "point-marker": "Marker",
            "point-lat": "Lat. point",
            "point-lon": "Lon. point",
            "point-color": "Color",
            "error": "A point with the given name already exists",
            "title-add-point": "Adding a point",
            "title-delete-point": "Delete a point",
        },
        "tab-add-trajectories":{
            "label": "Adding trajectories",
            "name-trajectory": "Name",
            "trajectory-file": "File",
            "trajectory-color": "Color",
            "error-name": "A trajectory with the given name already exists",
            "error-file": "Invalid file extension",
            "error-upload-file": "File needs to be uploaded",
            "title-add-trajectory": "Adding а trajectory",
            "title-delete-trajectory": "Deleting a trajectory",
            "children": "Select a file",
            "example": "Example:",
            "format": "Time, Longitude, Latitude, Hm",
            "format-example": "02:41:30, 24.8, -15.4, 300",
        },
        "download_window": {
            "label": "Date",
            "successаfuly": "File downloaded",
            "unsuccessаfuly": "The date is entered incorrectly",
            "repeat-action": "This file has already been downloaded",
            "error": "This file does not exist",
            "file-size": "Size (Gb): ",
            "unknown": "Unknown",
        },
        "open_window": {
            "label": "File",
        },
        "boot-progress-window":{
            "header": "Loading...",
        },
        "geo_stuctures_window":{
            "title": "Selecting an event tag",
        },
        "trajectory":{
            "hm": "hm",
            "hms": "Time",
            "error": "In this projection, trajectories are displayed incorrectly. Switch to Orthographic.",
            "show-tag-sip": "Show",
        }
    },
}
